In [1]:
import numpy as np
import scipy.misc
import pandas as pd
from math import sqrt
import math
from scipy import linalg
from collections import Counter

In [2]:
def svd(matrix):
    transposed = matrix.T
    
    multi1= transposed.dot(matrix)
    multi2= matrix.dot(transposed)
    
    eigen,evector = linalg.eig(multi1)
    #print(eigen)

    TeVector = evector.T
    #print(TeVector.dot(evector)) #checking that they are orthogonal
    s = []
    for i in eigen:
        s.append(sqrt(abs(i)))
    newS = np.diag(s)
    part= newS.dot(TeVector)
    U= matrix.dot(np.linalg.inv(part))
    print("*********************************************************")
    svdcustom=U.dot(newS.dot(TeVector))
    print(np.around(U, decimals=3))
    print(np.around(newS, decimals=3))
    print(np.around(TeVector, decimals=3))
    print(np.around(svdcustom, decimals=3))
    print("*********************************************************")
    U2,S2,V2 = np.linalg.svd(matrix)
    svdreal=U2.dot(np.diag(S2).dot(V2))
    print(np.around(U2, decimals=3))
    print(np.around(np.diag(S2), decimals=3))
    print(np.around(V2, decimals=3))
    print(np.around(svdreal, decimals=3))
    print("*********************************************************")
    print(matrix)
    


In [3]:
matrix= np.array([[0, 1, 1], [sqrt(2), 2, 0], [0, 1, 1]])
svd(matrix)

*********************************************************
[[-0.408 -0.     0.577]
 [-0.816  0.    -0.577]
 [-0.408 -0.     0.577]]
[[2.828 0.    0.   ]
 [0.    0.    0.   ]
 [0.    0.    1.414]]
[[-0.408 -0.866 -0.289]
 [ 0.707 -0.5    0.5  ]
 [-0.577 -0.     0.816]]
[[-0.     1.     1.   ]
 [ 1.414  2.     0.   ]
 [-0.     1.     1.   ]]
*********************************************************
[[-0.408  0.577 -0.707]
 [-0.816 -0.577  0.   ]
 [-0.408  0.577  0.707]]
[[2.828 0.    0.   ]
 [0.    1.414 0.   ]
 [0.    0.    0.   ]]
[[-0.408 -0.866 -0.289]
 [-0.577 -0.     0.816]
 [-0.707  0.5   -0.5  ]]
[[-0.     1.     1.   ]
 [ 1.414  2.    -0.   ]
 [-0.     1.     1.   ]]
*********************************************************
[[0.         1.         1.        ]
 [1.41421356 2.         0.        ]
 [0.         1.         1.        ]]
